#!/bin/bash
set -e

export PATH="$HOME/opt/cross/bin:$PATH"

rm -rf bin
mkdir bin
mkdir bin/tmp

nasm src/cpu/boot.s -f bin -o bin/tmp/boot.img

nasm "src/kernel_entry.s" -f elf -o "bin/tmp/kernel_entry.o"
i686-elf-gcc -ffreestanding -m32 -g -c 'src/kernel.c' -o bin/tmp/kernel.o

# Iterrupts
mkdir bin/tmp/interrupts
i686-elf-gcc -ffreestanding -m32 -g -c 'src/cpu/interrupts/idt.c' -o bin/tmp/interrupts/idt.o
nasm "src/cpu/interrupts/isr.s" -f elf -o "bin/tmp/interrupts/isr.o"
nasm "src/cpu/interrupts/pic.s" -f elf -o "bin/tmp/interrupts/pic.o"

#drivers
mkdir bin/tmp/drivers

#display
mkdir bin/tmp/drivers/display
i686-elf-gcc -ffreestanding -m32 -g -c 'src/drivers/display/text.c' -o bin/tmp/drivers/display/text.o

# link
i686-elf-ld -o bin/tmp/kernel.bin -Ttext 0x0500 \
\
'bin/tmp/kernel_entry.o' 'bin/tmp/kernel.o' \
'bin/tmp/interrupts/idt.o' 'bin/tmp/interrupts/isr.o' 'bin/tmp/interrupts/pic.o' \
'bin/tmp/drivers/display/text.o' \
\
--oformat binary

cat bin/tmp/boot.img bin/tmp/kernel.bin > bin/os.img

rm -rf bin/tmp

qemu-system-x86_64  -drive file=bin/os.img,format=raw
