#!/bin/bash
set -e

export PATH="$HOME/opt/cross/bin:$PATH"

rm -rf bin
mkdir bin
mkdir bin/tmp

nasm src/boot.s -f bin -o bin/tmp/boot.img

nasm "src/kernel_entry.asm" -f elf -o "bin/tmp/kernel_entry.o"
i686-elf-gcc -ffreestanding -m32 -g -c 'src/kernel.c' -o bin/tmp/kernel.o

# Iterrupts
mkdir bin/tmp/interrupts
i686-elf-gcc -ffreestanding -m32 -g -c 'src/interrupts/idt.c' -o bin/tmp/interrupts/idt.o

nasm "src/interrupts/isr.s" -f elf -o "bin/tmp/interrupts/isr.o"

# link
i686-elf-ld -o bin/tmp/kernel.bin -Ttext 0x0500 \
\
'bin/tmp/kernel_entry.o' 'bin/tmp/kernel.o' \
'bin/tmp/interrupts/idt.o' 'bin/tmp/interrupts/isr.o' \
\
--oformat binary

cat bin/tmp/boot.img bin/tmp/kernel.bin > bin/os.img

qemu-system-x86_64  -drive file=bin/os.img,format=raw
